- name: deploy LAMP stack on Ubuntu remote Server
  hosts: all
  become: true
  tasks:
    - name: Copy file with owner and permissions
      ansible.builtin.copy:
        src: /home/vagrant/LAMPstack.sh
        dest: /home/vagrant/LAMPstack.sh
        owner: vagrant
        group: vagrant
        mode: '0755'

    - name: install LAMP stack on Ubuntu server
      script: /home/vagrant/LAMPstack.sh


- name: Deploy cron job to check server uptime
  hosts: all
  become: true
  tasks:
    - name: Add cron job to check server uptime
      cron:
        name: "Check server uptime"
        minute: 0
        hour: 0
        job: "uptime >> /var/log/server_uptime.log"
